"""Final verification contract — completion criteria for objectives."""

from __future__ import annotations

import logging

from conductor.composer.models import ComposerPlan, TASK_NODE_STATUSES
from conductor.composer.storage import ComposerStorage

logger = logging.getLogger(__name__)

__all__ = ["VerificationContract", "ObjectiveCompletion"]


class ObjectiveCompletion:
    """Result of checking objective completion criteria."""

    def __init__(
        self,
        complete: bool,
        blocked_external: bool,
        failed: bool,
        reasons: list[str] | None = None,
    ) -> None:
        self.complete = complete
        self.blocked_external = blocked_external
        self.failed = failed
        self.reasons = reasons or []


class VerificationContract:
    """Checks whether an objective meets all completion criteria.

    Completion requires ALL of these proven:
    1. every required implementation task completed through Agents Gateway
    2. integration task completed
    3. each required verification command passed
    4. required live E2E passed
    5. final integration branch is recorded
    6. final integration commit SHA is recorded
    7. final report exists

    Missing credentials or unavailable external services → blocked_external.
    """

    def __init__(self, storage: ComposerStorage) -> None:
        self.storage = storage

    def check_completion(
        self,
        plan: dict,
        objective_id: str,
        agents_gateway_client=None,
    ) -> ObjectiveCompletion:
        """Check all completion criteria."""
        reasons: list[str] = []

        plan_tasks = plan.get("plan_tasks", [])

        implementation_tasks = [t for t in plan_tasks if t.get("task_type") != "integration"]
        integration_tasks = [t for t in plan_tasks if t.get("node_key") == "integration" or t.get("task_type") == "integration"]

        # Every implementation task must be completed
        incomplete_impls = [t for t in implementation_tasks if t.get("status") != "completed"]
        if incomplete_impls:
            reasons.append(f"Incomplete implementation tasks: {[t['node_key'] for t in incomplete_impls]}")

        for t in implementation_tasks:
            if t.get("status") == "blocked_external":
                return ObjectiveCompletion(
                    complete=False, blocked_external=True, failed=False,
                    reasons=["Implementation task blocked by external dependency: " + t.get("node_key", "")],
                )
            if t.get("status") == "failed":
                return ObjectiveCompletion(
                    complete=False, blocked_external=False, failed=True,
                    reasons=["Implementation task failed: " + t.get("node_key", "")],
                )

        # Integration task must be completed
        integration_task = integration_tasks[0] if integration_tasks else None
        if not integration_task:
            reasons.append("Integration task missing from plan")
        elif integration_task.get("status") != "completed":
            reasons.append("Integration task not completed")
            if integration_task.get("status") == "blocked_external":
                return ObjectiveCompletion(
                    complete=False, blocked_external=True, failed=False,
                    reasons=["Integration task externally blocked"],
                )
            if integration_task.get("status") == "failed":
                return ObjectiveCompletion(
                    complete=False, blocked_external=False, failed=True,
                    reasons=["Integration task failed"],
                )

        # Final branch and commit must be recorded
        if integration_task:
            if not integration_task.get("branch"):
                reasons.append("Final integration branch not recorded")
            if not integration_task.get("commit_sha"):
                reasons.append("Final integration commit SHA not recorded")

        # Report will be generated by _finalize_objective — don't require pre-existence here.
        # The _finalize_objective method generates the report as part of completion.

        # Verification commands — fetch actual results from Agents Gateway
        if agents_gateway_client:
            for pt in plan_tasks:
                gw_task_id = pt.get("agents_gateway_task_id")
                if not gw_task_id:
                    continue
                try:
                    gw_verif = agents_gateway_client.get_verification(gw_task_id)
                    if gw_verif:
                        commands = gw_verif.commands if hasattr(gw_verif, "commands") else []
                        for cmd in commands:
                            if cmd.get("required", False) and not cmd.get("passed", False):
                                reasons.append(
                                    f"Required verification '{cmd.get('name', cmd.get('command', ''))}'"
                                    f" not passed for {pt.get('node_key', '')}"
                                )
                except Exception:
                    pass

        # Check for external blockers (missing credentials, unavailable services)
        if agents_gateway_client:
            for pt in plan_tasks:
                verif = pt.get("verification", {})
                if isinstance(verif, dict) and verif.get("required", False):
                    live_e2e = verif.get("live_e2e")
                    if live_e2e and isinstance(live_e2e, dict) and live_e2e.get("required", False):
                        if live_e2e.get("status") == "blocked_external":
                            return ObjectiveCompletion(
                                complete=False, blocked_external=True, failed=False,
                                reasons=["Required live E2E blocked: " + live_e2e.get("reason", "missing credentials or unavailable service")],
                            )

        complete = len(reasons) == 0
        return ObjectiveCompletion(
            complete=complete,
            blocked_external=False,
            failed=False,
            reasons=reasons,
        )